python ./main.py --uv_size 2
python ./main.py --uv_size 4
python ./main.py --uv_size 8
python ./main.py --uv_size 16
python ./main.py --uv_size 32
python ./main.py --uv_size 64
python ./main.py --uv_size 128
python ./main.py --uv_size 256
python ./main.py --uv_size 512